name: 'PHP CS Fixer'
description: 'php code style fixer (php-cs-fixer)'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  dir:
    description: 'Folder to check code style'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
